Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,18 +1,21 @@
 name: Config Update
-on:
+
+于:
   push:
-    branches: [ main ]
+    分支: [ main ]
   workflow_dispatch:
   schedule:
     - cron: '0 12 * * *'
+
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
     - uses: actions/checkout@v2
     - name: "Setup sing-box"
       env:
-        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.11.4/sing-box_1.11.4_linux_amd64.deb"
+        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.27/sing-box_1.10.0-alpha.27_linux_amd64.deb"
       run: |
           set -Eeuo pipefail
           wget -O sing-box.deb $SING_BOX_DEB_URL
@@ -25,6 +28,22 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install pandas requests pyyaml
+    - name: Download content
+      run: |
+        URL="https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt"
+        OUTPUT_FILE="./rule/AdRules.txt"
+
+        curl -L $URL -o $OUTPUT_FILE
+
+        if [ -f "$OUTPUT_FILE" ]; then
+          echo "Download successful: $OUTPUT_FILE"
+        else
+          echo "Download failed."
+          exit 1
+        fi
+    - name: Convert AdRules DNS List to sing-box rule set
+      run: |
+        sing-box rule-set convert --type adguard --output ./rule/AdRules.srs ./rule/AdRules.txt
     - name: Run script
       run: python ../main.py
       working-directory: ./rule/
@@ -34,6 +53,9 @@ jobs:
         git config --global user.name "GitHub Action"
         git add ./rule/*.json
         git add ./rule/*.srs
+        git add ./rule/*.txt
+
+        # 检查是否有文件被修改
         if git diff --staged --quiet; then
           echo "No changes to commit"
           exit 0
